spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qr_code
    username: root
    password: rootroot

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
